/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ctmailinh.programme;

import com.mycompany.ctmailinh.libraly.HandleDate;
import com.mycompany.ctmailinh.libraly.QuerryAccount;
import com.mycompany.ctmailinh.libraly.QuerryCustomer;
import com.mycompany.ctmailinh.libraly.QuerryEmployee;
import com.mycompany.ctmailinh.object.Account;
import com.mycompany.ctmailinh.object.Customer;
import com.mycompany.ctmailinh.object.Employee;
import com.mycompany.ctmailinh.object.IdLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class EditMyAcc extends javax.swing.JFrame {
    IdLogin idlogin = new IdLogin();
    private int checkPermision = -1;
    private int idEdit = -1;
    /**
     * Creates new form EditMyAcc
     */
    public EditMyAcc() {
        initComponents();
        setLocationRelativeTo(null);
        addComboBoxDate();
        addComboBoxMonth();
        addComboBoxYear();
        Account account = QuerryAccount.findByIdFk(idlogin.getId());
        if (account.getCustomer_id() != 0) {
            checkPermision = 1;
            Customer cus = QuerryCustomer.find(account.getCustomer_id());
            idEdit = cus.getId();
            txtnameuseredit.setText(cus.getFullname());
            switch (cus.getGender()) {
                case "male" -> txtmaleuseredit.setSelected(true);
                case "female" -> txtfemaleuseredit.setSelected(true);
                default -> txtortheruseredit.setSelected(true);
            }
            String[] date = cus.getBirthday().split("-");
            HandleDate handle = new HandleDate();
            txtdateuseredit.setSelectedItem(handle.dateString(date[0]));
            txtmonthuseredit.setSelectedItem("Tháng "+handle.dateString(date[1]));
            txtyearuseredit.setSelectedItem(handle.dateString(date[2]));
            
            txtcmnduseredit.setText(cus.getID_card());
            txtphoneuseredit.setText(cus.getPhone());
            txtaddressuseredit.setText(cus.getAddress());
        } else if (account.getEmployee_id() != 0) {
            checkPermision = 2;
            Employee emp = QuerryEmployee.findById(idlogin.getId());
            idEdit = emp.getId();
            txtnameuseredit.setText(emp.getFullname());
            switch (emp.getGender()) {
                case "male" -> txtmaleuseredit.setSelected(true);
                case "female" -> txtfemaleuseredit.setSelected(true);
                default -> txtortheruseredit.setSelected(true);
            }
            String[] date = emp.getBirthday().split("-");
            HandleDate handle = new HandleDate();
            txtdateuseredit.setSelectedItem(handle.dateString(date[0]));
            txtmonthuseredit.setSelectedItem("Tháng "+handle.dateString(date[1]));
            txtyearuseredit.setSelectedItem(handle.dateString(date[2]));
            
            txtcmnduseredit.setText(emp.getID_card());
            txtphoneuseredit.setText(emp.getPhone());
            txtaddressuseredit.setText(emp.getAddress());
        }
    }

    private void addComboBoxDate() {
        for (int i = 1; i < 32; i++) {
            txtdateuseredit.addItem(String.valueOf(i));
        }
    }

    private void addComboBoxMonth() {
        for (int i = 1; i < 13; i++) {
            txtmonthuseredit.addItem("Tháng "+String.valueOf(i));
        }
    }

    private void addComboBoxYear() {
        for (int i = 2000; i < 2024; i++) {
            txtyearuseredit.addItem(String.valueOf(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnameuseredit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmaleuseredit = new javax.swing.JRadioButton();
        txtfemaleuseredit = new javax.swing.JRadioButton();
        txtortheruseredit = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtdateuseredit = new javax.swing.JComboBox<>();
        txtmonthuseredit = new javax.swing.JComboBox<>();
        txtyearuseredit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtcmnduseredit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddressuseredit = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtphoneuseredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Sửa thông tin cá nhân");

        jLabel2.setText("Tên người dùng:");

        jLabel3.setText("Giới tính:");

        buttonGroup1.add(txtmaleuseredit);
        txtmaleuseredit.setText("Nam");

        buttonGroup1.add(txtfemaleuseredit);
        txtfemaleuseredit.setText("Nữ");

        buttonGroup1.add(txtortheruseredit);
        txtortheruseredit.setText("Khác");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("CMND/CCCD:");

        jLabel6.setText("Địa chỉ:");

        txtaddressuseredit.setColumns(20);
        txtaddressuseredit.setRows(5);
        jScrollPane1.setViewportView(txtaddressuseredit);

        jLabel7.setText("Số điện thoại:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtdateuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmonthuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtyearuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtmaleuseredit)
                        .addGap(18, 18, 18)
                        .addComponent(txtfemaleuseredit)
                        .addGap(18, 18, 18)
                        .addComponent(txtortheruseredit))
                    .addComponent(txtcmnduseredit)
                    .addComponent(jScrollPane1)
                    .addComponent(txtnameuseredit)
                    .addComponent(txtphoneuseredit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnameuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmaleuseredit)
                    .addComponent(txtfemaleuseredit)
                    .addComponent(txtortheruseredit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdateuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmonthuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyearuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcmnduseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtphoneuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(213, 213, 213)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DetailMA detailma = new DetailMA();
        detailma.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = txtnameuseredit.getText();
        String cmnd = txtcmnduseredit.getText();
        String phone = txtphoneuseredit.getText();
        String address = txtaddressuseredit.getText();
        
        String gender = "";
        if (txtmaleuseredit.isSelected()) {
            gender = "male";
        } else if (txtfemaleuseredit.isSelected()) {
            gender = "female";
        } else {
            gender = "orther";
        }
        
        String checkdate = (String) txtdateuseredit.getSelectedItem();
        String date = "";
        if (checkdate.length() == 1) {
            date = "0"+checkdate;
        } else {
            date = checkdate;
        }
        String[] strMonth = ((String) txtmonthuseredit.getSelectedItem()).split(" ");
        String month = "";
        if (strMonth[1].length() == 1) {
            month = "0"+strMonth[1];
        } else {
            month = strMonth[1];
        }
        String year = (String) txtyearuseredit.getSelectedItem();
        
        switch (checkPermision) {
            case 1 -> {
                Customer cus = new Customer();
                cus.setFullname(name);
                cus.setGender(gender);
                cus.setAddress(address);
                cus.setBirthday(date+"-"+month+"-"+year);
                cus.setID_card(cmnd);
                cus.setPhone(phone);
                cus.setId(idEdit);
                QuerryCustomer.editById(cus);
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            }
            case 2 -> {
                Employee emp = new Employee();
                emp.setFullname(name);
                emp.setGender(gender);
                emp.setAddress(address);
                emp.setBirthday(date+"-"+month+"-"+year);
                emp.setID_card(cmnd);
                emp.setPhone(phone);
                emp.setId(idEdit);
                QuerryEmployee.update(emp);
                JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
            }
            default -> JOptionPane.showMessageDialog(rootPane, "Lỗi","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMyAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMyAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMyAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMyAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMyAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtaddressuseredit;
    private javax.swing.JTextField txtcmnduseredit;
    private javax.swing.JComboBox<String> txtdateuseredit;
    private javax.swing.JRadioButton txtfemaleuseredit;
    private javax.swing.JRadioButton txtmaleuseredit;
    private javax.swing.JComboBox<String> txtmonthuseredit;
    private javax.swing.JTextField txtnameuseredit;
    private javax.swing.JRadioButton txtortheruseredit;
    private javax.swing.JTextField txtphoneuseredit;
    private javax.swing.JComboBox<String> txtyearuseredit;
    // End of variables declaration//GEN-END:variables
}
