/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ctmailinh.programme;

import com.mycompany.ctmailinh.libraly.HandleDate;
import com.mycompany.ctmailinh.libraly.QuerryEmployee;
import com.mycompany.ctmailinh.libraly.QuerryHire;
import com.mycompany.ctmailinh.libraly.QuerryVehice;
import com.mycompany.ctmailinh.object.Employee;
import com.mycompany.ctmailinh.object.Hire;
import com.mycompany.ctmailinh.object.IdHireEmp;
import com.mycompany.ctmailinh.object.IdLogin;
import com.mycompany.ctmailinh.object.Vehice;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class EditEmpHire extends javax.swing.JFrame {
    IdHireEmp hire_id = new IdHireEmp();
    IdLogin idlogin = new IdLogin();
    /**
     * Creates new form EditEmpHire
     */
    public EditEmpHire() {
        initComponents();
        setLocationRelativeTo(null);
        addComboBoxDate();
        addComboBoxMonth();
        addComboBoxYear();
        addComboVehice();
        addComboDriver();
        Hire h = QuerryHire.findById(hire_id.getHire_id());
        
        String VeName = QuerryVehice.findReturnName(h.getVehice_id());
        txtvehicehireedit.setSelectedItem(h.getVehice_id()+" - "+VeName);
        
        String EmName = "Không có";
        if (h.getEmployee_id() != 0) {
            EmName = QuerryEmployee.findReturnName(h.getEmployee_id());
        }
        txtdriverhireedit.setSelectedItem(h.getEmployee_id()+" - "+EmName);
        String[] datetime = h.getStart_date().split(" ");
        String[] date = datetime[0].split("-");
        String[] time = datetime[1].split(":");
        HandleDate handle = new HandleDate();
        txtdatehireedit.setSelectedItem(handle.dateString(date[0]));
        txtmonthhireedit.setSelectedItem("Tháng "+handle.dateString(date[1]));
        txtyearhireedit.setSelectedItem(handle.dateString(date[2]));
        txthourhireedit.setText(time[0]);
        txtminishireedit.setText(time[1]);
    }

    private void addComboDriver() {
        List<Employee> ls = new ArrayList<>();
        ls = QuerryEmployee.selectDriver();
        txtdriverhireedit.addItem("0 - Không thuê");
        for (Employee l : ls) {
            txtdriverhireedit.addItem(String.valueOf(l.getId())+" - "+l.getFullname());
        }
    }
    
    private void addComboVehice() {
        List<Vehice> ls = new ArrayList<>();
        ls = QuerryVehice.findByStatus();
        for (Vehice vehice : ls) {
            txtvehicehireedit.addItem(String.valueOf(vehice.getId())+" - "+vehice.getName());
        }
    }
    
    private void addComboBoxDate() {
        for (int i = 1; i < 32; i++) {
            txtdatehireedit.addItem(String.valueOf(i));
        }
    }

    private void addComboBoxMonth() {
        for (int i = 1; i < 13; i++) {
            txtmonthhireedit.addItem("Tháng "+String.valueOf(i));
        }
    }

    private void addComboBoxYear() {
        for (int i = 2023; i < 2025; i++) {
            txtyearhireedit.addItem(String.valueOf(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtvehicehireedit = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtdriverhireedit = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txthourhireedit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtminishireedit = new javax.swing.JTextField();
        txtdatehireedit = new javax.swing.JComboBox<>();
        txtmonthhireedit = new javax.swing.JComboBox<>();
        txtyearhireedit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Phương tiện muốn thuê:");

        jLabel3.setText("Nhân viên lái xe:");

        jLabel4.setText("Thời gian bắt đầu:");

        txthourhireedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthourhireeditKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthourhireeditKeyReleased(evt);
            }
        });

        jLabel5.setText(":");

        txtminishireedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtminishireeditActionPerformed(evt);
            }
        });
        txtminishireedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtminishireeditKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtminishireeditKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtminishireeditKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txthourhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtminishireedit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdatehireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtmonthhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtyearhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdriverhireedit, javax.swing.GroupLayout.Alignment.LEADING, 0, 230, Short.MAX_VALUE)
                                    .addComponent(txtvehicehireedit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtvehicehireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdriverhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthourhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtminishireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdatehireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmonthhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyearhireedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Chỉnh sửa đăng ký");

        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthourhireeditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthourhireeditKeyPressed
        String minis = txthourhireedit.getText();
        String regex = "^[0-9]{2}$";
        Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE);
        Matcher matcher = pattern.matcher(minis);
        if (matcher.find()) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập số","Lỗi",JOptionPane.ERROR_MESSAGE);
            txthourhireedit.setText("");
        }
    }//GEN-LAST:event_txthourhireeditKeyPressed

    private void txthourhireeditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthourhireeditKeyReleased
        String minis = txthourhireedit.getText();
        if (minis.length() > 2) {
            txthourhireedit.setText("23");
        } else if (minis.length() == 2 ) {
            if (Integer.parseInt(minis) >= 24) {
                txthourhireedit.setText("23");
            }
        }
    }//GEN-LAST:event_txthourhireeditKeyReleased

    private void txtminishireeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtminishireeditActionPerformed

    }//GEN-LAST:event_txtminishireeditActionPerformed

    private void txtminishireeditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminishireeditKeyPressed
        String minis = txtminishireedit.getText();
        String regex = "^[0-9]{2}$";
        Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE);
        Matcher matcher = pattern.matcher(minis);
        if (matcher.find()) {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập số","Lỗi",JOptionPane.ERROR_MESSAGE);
            txtminishireedit.setText("");
        } else {

        }
    }//GEN-LAST:event_txtminishireeditKeyPressed

    private void txtminishireeditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminishireeditKeyReleased
        String minis = txtminishireedit.getText();
        if (minis.length() > 2) {
            txtminishireedit.setText("59");
        } else if (minis.length() == 2 ) {
            if (Integer.parseInt(minis) >= 60) {
                txtminishireedit.setText("59");
            }
        }
        //        else {
            //            txtminishireadd.setText("0"+minis);
            //        }
    }//GEN-LAST:event_txtminishireeditKeyReleased

    private void txtminishireeditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminishireeditKeyTyped

    }//GEN-LAST:event_txtminishireeditKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HireEmployee hitorycus = new HireEmployee();
        hitorycus.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] vehiceChoose = String.valueOf(txtvehicehireedit.getSelectedItem()).split(" - ");
        String[] driverChoose = String.valueOf(txtdriverhireedit.getSelectedItem()).split(" - ");

        String checkdate = String.valueOf(txtdatehireedit.getSelectedItem());
        String date = "";
        if (checkdate.length() == 1) {
            date = "0"+checkdate;
        } else {
            date = checkdate;
        }
        String[] checkmonth = String.valueOf(txtmonthhireedit.getSelectedItem()).split(" ");
        String month = "";
        if (checkmonth[1].length() == 1) {
            month = "0"+checkmonth[1];
        } else {
            month = checkmonth[1];
        }
        String year = String.valueOf(txtyearhireedit.getSelectedItem());

        if (!"".equals(txthourhireedit.getText()) && !"".equals(txtminishireedit.getText())) {
            Hire hire = new Hire();
            hire.setEmployee_id(Integer.parseInt(driverChoose[0]));
            hire.setStart_date(date+"-"+month+"-"+year+" "+txthourhireedit.getText()+":"+txtminishireedit.getText());
            hire.setVehice_id(Integer.parseInt(vehiceChoose[0]));
            hire.setId_hire(hire_id.getHire_id());
            QuerryHire.update(hire);
            JOptionPane.showMessageDialog(rootPane, "Sửa thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hãy điền đầy đủ thông tin","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmpHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmpHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmpHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmpHire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmpHire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> txtdatehireedit;
    private javax.swing.JComboBox<String> txtdriverhireedit;
    private javax.swing.JTextField txthourhireedit;
    private javax.swing.JTextField txtminishireedit;
    private javax.swing.JComboBox<String> txtmonthhireedit;
    private javax.swing.JComboBox<String> txtvehicehireedit;
    private javax.swing.JComboBox<String> txtyearhireedit;
    // End of variables declaration//GEN-END:variables
}
