/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ctmailinh.programme;

import com.mycompany.ctmailinh.libraly.CheckException;
import com.mycompany.ctmailinh.libraly.HandleDate;
import com.mycompany.ctmailinh.libraly.QuerryOffice;
import com.mycompany.ctmailinh.object.IdChooseNV;
import com.mycompany.ctmailinh.object.IdChooseOffice;
import com.mycompany.ctmailinh.object.Office;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class EditOffice extends javax.swing.JFrame {
    IdChooseNV idchooseNV = new IdChooseNV();
    /**
     * Creates new form EditOffice
     */
    public EditOffice() {
        initComponents();
        setLocationRelativeTo(null);
        addComboBoxDate();
        addComboBoxMonth();
        addComboBoxYear();
        IdChooseOffice idchooseOff = new IdChooseOffice();
        Office office = QuerryOffice.findByIdPk(idchooseOff.getIdChooseOffice());
        txtpositionofficeedit.setText(office.getPosition());
        
        String[] dateSt = office.getStart().split("-");
        HandleDate handle = new HandleDate();
        txtdateofficestedit.setSelectedItem(handle.dateString(dateSt[0]));
        txtmonthofficestedit.setSelectedItem("Tháng "+handle.dateString(dateSt[1]));
        txtyearofficestedit.setSelectedItem(handle.dateString(dateSt[2]));
        
        if (office.getEnd() != null) {
            String[] dateEd = office.getEnd().split("-");
            txtdateofficeededit.setSelectedItem(handle.dateString(dateEd[0]));
            txtmonthofficeededit.setSelectedItem("Tháng "+handle.dateString(dateEd[1]));
            txtyearofficeededit.setSelectedItem(handle.dateString(dateEd[2]));
        }
    }
    
    private void addComboBoxDate() {
        for (int i = 1; i < 32; i++) {
            txtdateofficestedit.addItem(String.valueOf(i));
            txtdateofficeededit.addItem(String.valueOf(i));
        }
    }

    private void addComboBoxMonth() {
        for (int i = 1; i < 13; i++) {
            txtmonthofficestedit.addItem("Tháng "+String.valueOf(i));
            txtmonthofficeededit.addItem("Tháng "+String.valueOf(i));
        }
    }

    private void addComboBoxYear() {
        for (int i = 2000; i < 2024; i++) {
            txtyearofficestedit.addItem(String.valueOf(i));
            txtyearofficeededit.addItem(String.valueOf(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtpositionofficeedit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdateofficestedit = new javax.swing.JComboBox<>();
        txtmonthofficestedit = new javax.swing.JComboBox<>();
        txtyearofficestedit = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtdateofficeededit = new javax.swing.JComboBox<>();
        txtmonthofficeededit = new javax.swing.JComboBox<>();
        txtyearofficeededit = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Chỉnh sửa vị trí");

        jLabel2.setText("Tên vị trí:");

        jLabel3.setText("Ngày bắt đầu:");

        txtdateofficestedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateofficesteditActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày kết thúc:");

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Trở về");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtdateofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmonthofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtyearofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdateofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtmonthofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtyearofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtpositionofficeedit))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpositionofficeedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdateofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmonthofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyearofficestedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdateofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmonthofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtyearofficeededit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdateofficesteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateofficesteditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateofficesteditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IdChooseOffice idchooseOff = new IdChooseOffice();
        idchooseOff.setIdChooseOffice(-1);
        DetailNV detailNV = new DetailNV();
        detailNV.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IdChooseOffice idchooseOff = new IdChooseOffice();
        String position = txtpositionofficeedit.getText();
        
        String checkDate =  String.valueOf(txtdateofficestedit.getSelectedItem());
        String dateSt = "";
        if (checkDate.length() == 1) {
            dateSt = "0"+checkDate;
        } else {
            dateSt = checkDate;
        }
        String[] checkMonth = String.valueOf(txtmonthofficestedit.getSelectedItem()).split(" ");
        String monthSt = "";
        if (checkMonth[1].length() == 1) {
            monthSt = "0"+checkMonth[1];
        } else {
            monthSt = checkMonth[1];
        }
        String yearSt = String.valueOf(txtyearofficestedit.getSelectedItem());
        
        String checkDateEd = String.valueOf(txtdateofficeededit.getSelectedItem());
        String dateEd = "";
        if (checkDateEd.length() == 1) {
            dateEd = "0"+checkDateEd;
        } else {
            dateEd = checkDateEd;
        }
        String[] checkMonthEd = String.valueOf(txtmonthofficeededit.getSelectedItem()).split(" ");
        String monthEd = "";
        if (checkMonthEd[1].length() == 1) {
            monthEd = "0"+checkMonthEd[1];
        } else {
            monthEd = checkMonthEd[1];
        }
        String yearEd = String.valueOf(txtyearofficeededit.getSelectedItem());
        
        if (!position.equals("")) {
            Office office = new Office();
            office.setId_office(idchooseOff.getIdChooseOffice());
            office.setId_employee(idchooseNV.getIdChooseNV());
            office.setPosition(position);
            office.setStart(dateSt+"-"+monthSt+"-"+yearSt);
            if (!checkDateEd.equalsIgnoreCase("1") && !checkMonthEd[1].equalsIgnoreCase("1") && !yearEd.equalsIgnoreCase("2000")) {
                office.setEnd(dateEd+"-"+monthEd+"-"+yearEd);
            }
            QuerryOffice.update(office);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập thông tin sửa","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> txtdateofficeededit;
    private javax.swing.JComboBox<String> txtdateofficestedit;
    private javax.swing.JComboBox<String> txtmonthofficeededit;
    private javax.swing.JComboBox<String> txtmonthofficestedit;
    private javax.swing.JTextField txtpositionofficeedit;
    private javax.swing.JComboBox<String> txtyearofficeededit;
    private javax.swing.JComboBox<String> txtyearofficestedit;
    // End of variables declaration//GEN-END:variables
}
